### PR TITLE
Add support for running on .NET 7.0

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by CharliePoole** [comment]
@kant2002 Thanks for your contribution! I'm not sure about the failure in AppVeyor, but it may be that the numbering of builds has changed and some older builds (with higher numbers) need to be removed from MyGet. I'll take a look at that.

I'd actually prefer to fix this problem once and for all rather than continuing to add new lines in Runners.cs. This was done for nunit/nunit-console#1179 and should be replicated for the testcentric engine as well. I'm splitting time between the two projects and haven't had time to do that.

We can go two ways on this PR. If you're willing and have time to port the above PR to testcentric, that would be great. However, if you prefer, I can merge this once the CI problem is fixed and we can wait until someone has time do the more complete fix.

**Comment by CharliePoole** [comment]
@kant2002 Waiting to hear which way you'd like to go on this.

**Comment by kant2002** [comment]
@CharliePoole Can we go fast way first. I would try properly fix issue, but I have to allocate some time. I find this issue during evaluation of the TestCentric, so proper fix was out of scope, but I understand why do you want proper fix.

**Comment by CharliePoole** [comment]
Sure... I'll merge this after I fix the CI build and the gui alpha5 release will include it. I'll also add a new issue for the proper fix.

**Comment by CharliePoole** [comment]
This was a real can of worms! I'll summarize the problems for future reference.

1. Because multiple packages are involved and all are in the development stage, I have to manually maintain the exact versions to be referenced. I had forgotten to pin the version in use and it was automatically deleted.

2. Testcentric-engine is now using the latest nunit api dev package, 4.0.0-dev00102, which I will pin.

3. However, that package had a change adding a property to RuntimeFrameworkService. I have temporarily added the property with an exception being thrown, since we don't actually use it right now.

4. Moreover, some of the extensions used in our CI testing also were using the same, obsolete build of the API. So I have temporarily eliminated those tests from the build. This includes extensions NUnitProjectLoader, Net20PluggableAgent and NetCore21Pluggable agent.

5. With all the above in place, the PR was able to pass its tests and is now merged.

I'll create issues for removing these temporary fixes in favor of more robust changes.

**Pull request merged**
